apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: test-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi-kenzo
spec:
 accessModes:
  - ReadWriteMany
 resources:
   requests:
     storage: 1Gi
